<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_You selected Cancel</name>
   <tag></tag>
   <elementGuidId>19a7c330-06de-445b-a53b-255660e528e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='confirmResult']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirmResult</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4925df49-473d-4e2c-9db0-a518a9efeadd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmResult</value>
      <webElementGuid>c58250c0-0b8b-40a9-a02d-bb6ab571e17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-success</value>
      <webElementGuid>9bec667b-c7a2-4724-b69a-42397c2aad24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You selected Cancel</value>
      <webElementGuid>89695f3d-49ba-407e-b99e-9a8dc3f28708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmResult&quot;)</value>
      <webElementGuid>1aeb7a54-37c6-4223-a521-f48949b9eae3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='confirmResult']</value>
      <webElementGuid>7d5a1b1d-46bc-4049-87f8-17926bec587c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='javascriptAlertsWrapper']/div[3]/div/span[2]</value>
      <webElementGuid>5f5fa247-d5f8-4de2-8247-b09a394b50e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>b6963492-eebe-4b61-8964-15c46a6a6e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'confirmResult' and (text() = 'You selected Cancel' or . = 'You selected Cancel')]</value>
      <webElementGuid>b046d657-da0d-478a-bb88-257572034c24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
