<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Where</name>
   <tag></tag>
   <elementGuidId>a4aa0173-a159-4b9a-8cb1-52d17294aa1c</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Airbnb  Holiday rentals, cabins, beach houses  more/input_Where_query.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bigsearch-query-location-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bigsearch-query-location-input']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Airbnb  Holiday rentals, cabins, beach houses  more/input_Where_query.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53433380-2a89-4ce6-be94-517904643cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ifqrz18 atm_9s_1ulexfb atm_3f_idpfg4 atm_gi_idpfg4 atm_l8_idpfg4 atm_vy_1osqo2v atm_26_glywfm atm_c8_fkimz8 atm_g3_11yl58k atm_fr_4ym3tx atm_cs_qo5vgd atm_7l_18pqv07 atm_sq_1l2sidv atm_c8_fkimz8_17x46du atm_g3_11yl58k_17x46du atm_fr_4ym3tx_17x46du atm_cs_atq67q_17x46du atm_7l_o7x4t6_17x46du atm_c8_fkimz8_y5ttn9 atm_g3_11yl58k_y5ttn9 atm_fr_4ym3tx_y5ttn9 atm_cs_atq67q_y5ttn9 atm_7l_o7x4t6_y5ttn9 atm_c8_fkimz8_1k1obal atm_g3_11yl58k_1k1obal atm_fr_4ym3tx_1k1obal atm_cs_atq67q_1k1obal atm_7l_o7x4t6_1k1obal atm_c8_fkimz8_m14rgb atm_g3_11yl58k_m14rgb atm_fr_4ym3tx_m14rgb atm_cs_atq67q_m14rgb atm_7l_o7x4t6_m14rgb atm_c8_fkimz8_3ykvna atm_g3_11yl58k_3ykvna atm_fr_4ym3tx_3ykvna atm_cs_atq67q_3ykvna atm_7l_o7x4t6_3ykvna atm_9s_glywfm_136h51u atm_kd_glywfm_pfnrn2 atm_ll_1fwxnve_c2x6ez dir dir-ltr</value>
      <webElementGuid>105e13a2-60c6-44d5-9f3c-aee6706b931b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>0b0166eb-97e6-46cd-aeef-c6738168930a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>80305c45-10d6-4dca-b81f-c03a948b3522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5093a029-764d-4d9b-aba5-08fedb4fe973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ac47caed-b563-461f-a042-0ff6f7d33422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bigsearch-query-location-input</value>
      <webElementGuid>9fda0278-f952-434f-ab6c-7528b7ac8a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>query</value>
      <webElementGuid>4190db2e-4dd0-4e2e-aeff-c6fe7f0c96b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bigsearch-query-location-description</value>
      <webElementGuid>923b5e89-0daa-47a8-8d99-bc5a9c8f57c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search destinations</value>
      <webElementGuid>d072de0b-611e-4048-bee8-421256233f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>structured-search-input-field-query</value>
      <webElementGuid>90ef8cf8-ea9a-4627-9e8e-0b7e276aabd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigsearch-query-location-input&quot;)</value>
      <webElementGuid>2030b728-840e-4109-8f1e-ecd383e92e5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bigsearch-query-location-input']</value>
      <webElementGuid>65de6291-fbac-4ec9-9d87-2829d62a4d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-tabpanel']/div/div/div/label/div/input</value>
      <webElementGuid>a8d376f6-0814-42be-a488-ae754379fd61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/input</value>
      <webElementGuid>95af5690-21d7-4f4b-8e1e-76453c9aacf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'bigsearch-query-location-input' and @name = 'query' and @placeholder = 'Search destinations']</value>
      <webElementGuid>b2825281-1593-4f0d-b73a-bf4f7382d15b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
