<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create new user</name>
   <tag></tag>
   <elementGuidId>31893f21-33c2-4cc2-91c3-6882aacb7438</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#create-user</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='create-user']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c937404-a587-4408-abbd-0db8e015036d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create-user</value>
      <webElementGuid>668c1a59-1c41-4a70-9e65-ee64f081fe7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-corner-all ui-widget</value>
      <webElementGuid>acf551c5-fb2c-476d-abbb-e2262b9a5647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create new user</value>
      <webElementGuid>c40b56a9-16d5-47cb-b839-b14c0dedd553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create-user&quot;)</value>
      <webElementGuid>f5e5d868-d83e-4211-8056-4f15687af0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dialogbox/WebBase/Page_Dialog Boxes - GlobalSQA/iframe_demo-frame lazyloaded</value>
      <webElementGuid>3abaca7e-d4b5-492e-8fe7-d7817d36ed3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='create-user']</value>
      <webElementGuid>7691a4ea-c834-42c4-b4e7-01f9d8bb35fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>aad80968-fdf8-46b3-a333-6694d9a08c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'create-user' and (text() = 'Create new user' or . = 'Create new user')]</value>
      <webElementGuid>17164fe4-f14f-4ae5-9df4-e7988131746a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
