<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ui-resizable-handle ui-resizable-w</name>
   <tag></tag>
   <elementGuidId>85c0032f-d5b4-46df-ab5f-2961340f14ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ui-resizable-handle.ui-resizable-w</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f0599c5f-063f-4794-bdbc-a9ca8d32726c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-resizable-handle ui-resizable-w</value>
      <webElementGuid>7424c204-3755-4e8e-abda-fe6fdd321fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;ui-dialog ui-corner-all ui-widget ui-widget-content ui-front ui-dialog-buttons ui-draggable ui-resizable&quot;]/div[@class=&quot;ui-resizable-handle ui-resizable-w&quot;]</value>
      <webElementGuid>ee9d6c8d-043d-4083-abb8-eccbe7026a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dialogbox/WebBase/Page_Dialog Boxes - GlobalSQA/iframe_demo-frame lazyloaded</value>
      <webElementGuid>1938474c-5579-4ed6-b30d-fcec550f9e0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]</value>
      <webElementGuid>d2f87ea9-be8f-4e5e-9de1-18a83ee307a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
