<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_demo-frame lazyloaded</name>
   <tag></tag>
   <elementGuidId>026af9f1-0959-451d-8262-24d2c9a4dcad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.demo-frame.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='post-2663']/div[2]/div/div/div/p/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e8c9c95c-7426-4e59-95e9-a154f94f721e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>700</value>
      <webElementGuid>1cbf2990-1d10-454a-8196-cbe84385d5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>238bf5f7-b216-459e-ae6a-a3c86955bee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>../../demoSite/practice/dialog/modal-form.html</value>
      <webElementGuid>0b400334-f261-464a-9dc6-9e7c1cbd1641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>demo-frame lazyloaded</value>
      <webElementGuid>c2044f54-5df4-47e5-9cab-012d33cd4b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==</value>
      <webElementGuid>3fe3949e-4e74-46ad-b841-25f4d34cebf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-2663&quot;)/div[@class=&quot;twelve columns&quot;]/div[@class=&quot;newtabs horizontal&quot;]/div[@class=&quot;resp-tabs-container&quot;]/div[@class=&quot;single_tab_div resp-tab-content resp-tab-content-active&quot;]/p[1]/iframe[@class=&quot;demo-frame lazyloaded&quot;]</value>
      <webElementGuid>5fe63192-64b8-45a4-ba06-1e39d8f69354</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-2663']/div[2]/div/div/div/p/iframe</value>
      <webElementGuid>0cd41084-9bae-4a61-8b3b-ed58e1a05acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/iframe</value>
      <webElementGuid>ed8b52aa-c575-493d-8e32-7d43e744aefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==']</value>
      <webElementGuid>ca99fd87-9682-4a4a-9d98-c8bc2a45c214</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
