<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_mayur</name>
   <tag></tag>
   <elementGuidId>d8c10359-68d6-46e7-9fff-212f038fa334</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='users']/tbody/tr[2]/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>535ee9aa-698c-44e6-932a-a624fb4e3326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mayur</value>
      <webElementGuid>abf4a41e-9655-4d44-859f-120e1905ca2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;users&quot;)/tbody[1]/tr[2]/td[1]</value>
      <webElementGuid>b01141fa-be96-4dac-8a8c-5c5b591ae225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dialogbox/WebBase/Page_Dialog Boxes - GlobalSQA/iframe_demo-frame lazyloaded</value>
      <webElementGuid>eeda6856-784e-41c7-ab0d-31fefd8486ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='users']/tbody/tr[2]/td</value>
      <webElementGuid>c11dbddb-90b6-4b48-a905-94385364420a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td</value>
      <webElementGuid>83c1f09d-375e-4fbd-a6ed-3d05966bd18f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'mayur' or . = 'mayur')]</value>
      <webElementGuid>afa984c9-a1d2-47f5-98db-0d7c24752e45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
